##   INSTALLING NUMPY

In [10]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [11]:
import numpy as np

In [12]:
np.__version__

'2.1.3'

In [13]:
import sys
sys.version

'3.13.5 | packaged by Anaconda, Inc. | (main, Jun 12 2025, 16:37:03) [MSC v.1929 64 bit (AMD64)]'

## NUMPY Functions

In [8]:
## CREATING ARRAY

In [14]:
my_list=[0,1,2,3,4,5]
my_list

[0, 1, 2, 3, 4, 5]

In [15]:
type(my_list)

list

In [16]:
arr = np.array(my_list)       #typecasting list to array by using array function

In [17]:
arr

array([0, 1, 2, 3, 4, 5])

In [18]:
type(arr)

numpy.ndarray

In [19]:
type(my_list)

list

## arange Function

In [20]:
np.arange(15)    #arange function

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [21]:
np.arange(3.0)

array([0., 1., 2.])

In [24]:
np.arange(0,5)

array([0, 1, 2, 3, 4])

In [25]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [26]:
np.arange(20,10)     #1st arg < 2nd arg

array([], dtype=int64)

In [27]:
np.arange(-10,20)

array([-10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,
         3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,  14,  15,
        16,  17,  18,  19])

In [28]:
np.arange(-20,-10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11])

In [29]:
np.arange(10,10)

array([], dtype=int64)

In [30]:
np.arange()    #in arange function atleast one argument is required

TypeError: arange() requires stop to be specified.

In [31]:
np.arange(10,30,5)

array([10, 15, 20, 25])

In [32]:
np.arange(10,30,5,4)  # in arange function three arguments are the maximum count 

TypeError: Cannot interpret '4' as a data type

In [33]:
arr = np.arange(-30,20)
arr

array([-30, -29, -28, -27, -26, -25, -24, -23, -22, -21, -20, -19, -18,
       -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,  -7,  -6,  -5,
        -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,
         9,  10,  11,  12,  13,  14,  15,  16,  17,  18,  19])

In [34]:
import numpy as np

## zeros Function

In [35]:
np.zeros(3)  #zeros()  #parameter tunning         # zeros function by default reads and gives output as the value (float)

array([0., 0., 0.])

In [36]:
np.zeros(5, dtype=int)   #hyperparameter tunning

array([0, 0, 0, 0, 0])

In [37]:
np.zeros((2,2),dtype=int)     #(2,2) is read by 2rows & 2columns

array([[0, 0],
       [0, 0]])

In [38]:
zero=np.zeros([2,2])
print(zero)
print(type(zero))

[[0. 0.]
 [0. 0.]]
<class 'numpy.ndarray'>


In [39]:
zero=np.zeros([2,2])
print(zero)
print('####')
print(type(zero))

[[0. 0.]
 [0. 0.]]
####
<class 'numpy.ndarray'>


In [40]:
np.zeros((2,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [42]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [43]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [44]:
np.zeros((10,30))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0

In [45]:
n=(6,7)
n1=(6,8)

In [46]:
np.zeros(n)

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [47]:
np.zeros(n1)

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [48]:
print(np.zeros(n))
print(np.zeros(n1))

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


# ones Function

In [49]:
n

(6, 7)

In [50]:
n1

(6, 8)

In [51]:
np.ones(4)     #ones()

array([1., 1., 1., 1.])

In [52]:
np.ones(4, dtype=int)

array([1, 1, 1, 1])

In [53]:
n

(6, 7)

In [54]:
n1

(6, 8)

In [55]:
np.ones(n)

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [56]:
np.ones(n1)

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [57]:
np.ones((4,4),dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [58]:
np.

SyntaxError: invalid syntax (2469254449.py, line 1)

In [85]:
# twos and threes function doesn't exsist

In [59]:
np.twos(2,3)

AttributeError: module 'numpy' has no attribute 'twos'

In [60]:
np.threes(2,3)

AttributeError: module 'numpy' has no attribute 'threes'

# range Function

In [61]:
range(0,5)

range(0, 5)

In [62]:
r=range(5)
r

range(0, 5)

In [63]:
for i in r:
    print(i)

0
1
2
3
4


In [64]:
for i in r:
    print(r)

range(0, 5)
range(0, 5)
range(0, 5)
range(0, 5)
range(0, 5)


In [65]:
list(range(5))

[0, 1, 2, 3, 4]

In [66]:
range(1,10)

range(1, 10)

In [67]:
list(range(1,10))

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [68]:
list(range(1,10,3))

[1, 4, 7]

In [69]:
y=list(range(12))
y

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]

In [70]:
rand(3,2)

NameError: name 'rand' is not defined

In [71]:
round.rand(3,2)

AttributeError: 'builtin_function_or_method' object has no attribute 'rand'

In [72]:
np.random.rand(5)

array([0.26277704, 0.40764101, 0.41777583, 0.28259942, 0.10983367])

In [74]:
np.rand(4)

AttributeError: module 'numpy' has no attribute 'rand'

In [75]:
np.random.rand(2,4)

array([[0.89978098, 0.28248743, 0.60366211, 0.99309301],
       [0.58399087, 0.87504479, 0.43225218, 0.83715611]])

In [76]:
np.random.randint(2,4)

3

In [77]:
np.random.randint(0,1)

0

In [78]:
np.random.randint(10,30,5)

array([26, 22, 13, 29, 19], dtype=int32)

In [79]:
np.random.randint(2.9)

1

In [80]:
np.random.randint(10,20,30)

array([16, 14, 12, 14, 14, 16, 17, 19, 14, 16, 14, 13, 18, 19, 18, 17, 15,
       10, 13, 11, 13, 11, 10, 14, 11, 18, 19, 15, 16, 14], dtype=int32)

In [81]:
np.random.randint(-30,20,10)

array([ -9, -23,   7, -25, -18,  -6,  12,   2,  -3, -25], dtype=int32)

In [82]:
np.random.randint(30,20,10)

ValueError: low >= high

In [83]:
np.random.randint(1,100,(12,12))

array([[57, 73, 84, 28, 21, 47, 30, 53, 47, 67, 18, 30],
       [24, 48, 69, 96, 50,  9, 13, 25, 92, 94, 76, 92],
       [30, 89, 94, 24, 40, 96, 39, 28, 88, 88, 20, 17],
       [24, 90, 74, 52, 60,  1, 58, 47, 62, 51, 44, 53],
       [46, 22, 16, 41,  8, 62, 46, 40, 28, 13,  1, 73],
       [77,  6, 19, 28, 47, 47, 50, 46, 66, 60, 41, 92],
       [56, 14, 12, 17,  5,  2,  5, 10, 72, 46, 40, 65],
       [65, 13, 94, 15, 41, 13, 67, 88, 76, 33, 61, 47],
       [30, 55,  2, 72, 38, 98, 15,  9, 17, 85, 31,  6],
       [61, 69, 75, 65, 58, 38, 76, 28, 15, 19, 36, 78],
       [34, 13, 54, 38, 23,  4, 21, 49, 38, 64, 63, 67],
       [94, 54, 48, 70, 90, 55, 38, 16, 40, 54, 75,  2]], dtype=int32)

In [84]:
np.arange(0,15).reshape(3,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [85]:
np.arange(1,13).reshape(12,1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

In [86]:
b = np.random.randint(10,20,(4,5))
print(b)

[[11 14 17 10 18]
 [13 13 18 19 13]
 [18 11 12 11 14]
 [14 11 10 18 17]]


## Slicing & Indexing Function

In [87]:
type(b)

numpy.ndarray

In [89]:
b

array([[11, 14, 17, 10, 18],
       [13, 13, 18, 19, 13],
       [18, 11, 12, 11, 14],
       [14, 11, 10, 18, 17]], dtype=int32)

In [88]:
b[:]

array([[11, 14, 17, 10, 18],
       [13, 13, 18, 19, 13],
       [18, 11, 12, 11, 14],
       [14, 11, 10, 18, 17]], dtype=int32)

In [90]:
b[1:3]

array([[13, 13, 18, 19, 13],
       [18, 11, 12, 11, 14]], dtype=int32)

In [91]:
b

array([[11, 14, 17, 10, 18],
       [13, 13, 18, 19, 13],
       [18, 11, 12, 11, 14],
       [14, 11, 10, 18, 17]], dtype=int32)

In [93]:
b[1,2]

np.int32(18)

In [94]:
b

array([[11, 14, 17, 10, 18],
       [13, 13, 18, 19, 13],
       [18, 11, 12, 11, 14],
       [14, 11, 10, 18, 17]], dtype=int32)

In [95]:
b[1,3]

np.int32(19)

In [96]:
b[-1,1]

np.int32(11)

In [97]:
b

array([[11, 14, 17, 10, 18],
       [13, 13, 18, 19, 13],
       [18, 11, 12, 11, 14],
       [14, 11, 10, 18, 17]], dtype=int32)

In [99]:
b[2:3]

array([[18, 11, 12, 11, 14]], dtype=int32)

In [100]:
b

array([[11, 14, 17, 10, 18],
       [13, 13, 18, 19, 13],
       [18, 11, 12, 11, 14],
       [14, 11, 10, 18, 17]], dtype=int32)

In [101]:
b[0:-2]

array([[11, 14, 17, 10, 18],
       [13, 13, 18, 19, 13]], dtype=int32)

In [102]:
b

array([[11, 14, 17, 10, 18],
       [13, 13, 18, 19, 13],
       [18, 11, 12, 11, 14],
       [14, 11, 10, 18, 17]], dtype=int32)

In [105]:
b[0,2]

np.int32(17)

In [106]:
b

array([[11, 14, 17, 10, 18],
       [13, 13, 18, 19, 13],
       [18, 11, 12, 11, 14],
       [14, 11, 10, 18, 17]], dtype=int32)

In [108]:
b[-3,-5]

np.int32(13)

In [109]:
np.random.randint(10,20,(4,4))

array([[17, 17, 17, 16],
       [15, 15, 19, 11],
       [18, 10, 13, 18],
       [18, 19, 13, 17]], dtype=int32)

In [110]:
b

array([[11, 14, 17, 10, 18],
       [13, 13, 18, 19, 13],
       [18, 11, 12, 11, 14],
       [14, 11, 10, 18, 17]], dtype=int32)

In [111]:
b[-4,-2]

np.int32(10)

In [112]:
b

array([[11, 14, 17, 10, 18],
       [13, 13, 18, 19, 13],
       [18, 11, 12, 11, 14],
       [14, 11, 10, 18, 17]], dtype=int32)

In [114]:
b[-4:2]

array([[11, 14, 17, 10, 18],
       [13, 13, 18, 19, 13]], dtype=int32)

In [115]:
b[:]

array([[11, 14, 17, 10, 18],
       [13, 13, 18, 19, 13],
       [18, 11, 12, 11, 14],
       [14, 11, 10, 18, 17]], dtype=int32)

## Operations

In [116]:
a=np.random.randint(10,20,10)
a

array([19, 17, 17, 16, 10, 10, 10, 10, 19, 17], dtype=int32)

In [117]:
id(a)

1811473932880

In [118]:
arr

array([-30, -29, -28, -27, -26, -25, -24, -23, -22, -21, -20, -19, -18,
       -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,  -7,  -6,  -5,
        -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,
         9,  10,  11,  12,  13,  14,  15,  16,  17,  18,  19])

In [122]:
arr2 = np.random.randint(0,100,(10,10))
arr2

array([[70, 81, 99, 81, 53, 18, 39, 35, 11, 21],
       [ 7, 83, 42, 63, 96, 40, 11, 55, 99, 96],
       [74, 33, 90,  8, 81, 33, 36, 94, 53, 76],
       [45, 14, 87, 89,  9, 78, 80, 69,  5, 23],
       [16,  8, 24, 42, 73, 24, 59, 76, 43, 37],
       [55, 55, 26, 22,  1, 22, 22, 46, 81, 23],
       [89, 34, 20, 77,  6, 74, 35, 53, 26, 97],
       [27, 55, 86, 28, 25, 67, 75, 61, 88, 55],
       [80, 27, 74, 86, 93, 34, 70, 54, 93, 87],
       [54, 32, 49, 26, 48, 54, 18, 77, 63,  0]], dtype=int32)

In [123]:
arr

array([-30, -29, -28, -27, -26, -25, -24, -23, -22, -21, -20, -19, -18,
       -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,  -7,  -6,  -5,
        -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,
         9,  10,  11,  12,  13,  14,  15,  16,  17,  18,  19])

In [124]:
arr[:]

array([-30, -29, -28, -27, -26, -25, -24, -23, -22, -21, -20, -19, -18,
       -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,  -7,  -6,  -5,
        -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,
         9,  10,  11,  12,  13,  14,  15,  16,  17,  18,  19])

In [125]:
arr

array([-30, -29, -28, -27, -26, -25, -24, -23, -22, -21, -20, -19, -18,
       -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,  -7,  -6,  -5,
        -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,
         9,  10,  11,  12,  13,  14,  15,  16,  17,  18,  19])

In [126]:
arr[:4]

array([-30, -29, -28, -27])

In [127]:
arr2[:]

array([[70, 81, 99, 81, 53, 18, 39, 35, 11, 21],
       [ 7, 83, 42, 63, 96, 40, 11, 55, 99, 96],
       [74, 33, 90,  8, 81, 33, 36, 94, 53, 76],
       [45, 14, 87, 89,  9, 78, 80, 69,  5, 23],
       [16,  8, 24, 42, 73, 24, 59, 76, 43, 37],
       [55, 55, 26, 22,  1, 22, 22, 46, 81, 23],
       [89, 34, 20, 77,  6, 74, 35, 53, 26, 97],
       [27, 55, 86, 28, 25, 67, 75, 61, 88, 55],
       [80, 27, 74, 86, 93, 34, 70, 54, 93, 87],
       [54, 32, 49, 26, 48, 54, 18, 77, 63,  0]], dtype=int32)

In [128]:
arr2[0:5]

array([[70, 81, 99, 81, 53, 18, 39, 35, 11, 21],
       [ 7, 83, 42, 63, 96, 40, 11, 55, 99, 96],
       [74, 33, 90,  8, 81, 33, 36, 94, 53, 76],
       [45, 14, 87, 89,  9, 78, 80, 69,  5, 23],
       [16,  8, 24, 42, 73, 24, 59, 76, 43, 37]], dtype=int32)

In [129]:
arr2

array([[70, 81, 99, 81, 53, 18, 39, 35, 11, 21],
       [ 7, 83, 42, 63, 96, 40, 11, 55, 99, 96],
       [74, 33, 90,  8, 81, 33, 36, 94, 53, 76],
       [45, 14, 87, 89,  9, 78, 80, 69,  5, 23],
       [16,  8, 24, 42, 73, 24, 59, 76, 43, 37],
       [55, 55, 26, 22,  1, 22, 22, 46, 81, 23],
       [89, 34, 20, 77,  6, 74, 35, 53, 26, 97],
       [27, 55, 86, 28, 25, 67, 75, 61, 88, 55],
       [80, 27, 74, 86, 93, 34, 70, 54, 93, 87],
       [54, 32, 49, 26, 48, 54, 18, 77, 63,  0]], dtype=int32)

In [131]:
arr2[1,4]

np.int32(96)

In [132]:
arr2[-5,5]

np.int32(22)

In [133]:
arr2[-5,-5]

np.int32(22)

In [134]:
arr2

array([[70, 81, 99, 81, 53, 18, 39, 35, 11, 21],
       [ 7, 83, 42, 63, 96, 40, 11, 55, 99, 96],
       [74, 33, 90,  8, 81, 33, 36, 94, 53, 76],
       [45, 14, 87, 89,  9, 78, 80, 69,  5, 23],
       [16,  8, 24, 42, 73, 24, 59, 76, 43, 37],
       [55, 55, 26, 22,  1, 22, 22, 46, 81, 23],
       [89, 34, 20, 77,  6, 74, 35, 53, 26, 97],
       [27, 55, 86, 28, 25, 67, 75, 61, 88, 55],
       [80, 27, 74, 86, 93, 34, 70, 54, 93, 87],
       [54, 32, 49, 26, 48, 54, 18, 77, 63,  0]], dtype=int32)

In [140]:
arr2[::-1]

array([[54, 32, 49, 26, 48, 54, 18, 77, 63,  0],
       [80, 27, 74, 86, 93, 34, 70, 54, 93, 87],
       [27, 55, 86, 28, 25, 67, 75, 61, 88, 55],
       [89, 34, 20, 77,  6, 74, 35, 53, 26, 97],
       [55, 55, 26, 22,  1, 22, 22, 46, 81, 23],
       [16,  8, 24, 42, 73, 24, 59, 76, 43, 37],
       [45, 14, 87, 89,  9, 78, 80, 69,  5, 23],
       [74, 33, 90,  8, 81, 33, 36, 94, 53, 76],
       [ 7, 83, 42, 63, 96, 40, 11, 55, 99, 96],
       [70, 81, 99, 81, 53, 18, 39, 35, 11, 21]], dtype=int32)

In [141]:
arr2

array([[70, 81, 99, 81, 53, 18, 39, 35, 11, 21],
       [ 7, 83, 42, 63, 96, 40, 11, 55, 99, 96],
       [74, 33, 90,  8, 81, 33, 36, 94, 53, 76],
       [45, 14, 87, 89,  9, 78, 80, 69,  5, 23],
       [16,  8, 24, 42, 73, 24, 59, 76, 43, 37],
       [55, 55, 26, 22,  1, 22, 22, 46, 81, 23],
       [89, 34, 20, 77,  6, 74, 35, 53, 26, 97],
       [27, 55, 86, 28, 25, 67, 75, 61, 88, 55],
       [80, 27, 74, 86, 93, 34, 70, 54, 93, 87],
       [54, 32, 49, 26, 48, 54, 18, 77, 63,  0]], dtype=int32)

In [142]:
arr2[::-2]

array([[54, 32, 49, 26, 48, 54, 18, 77, 63,  0],
       [27, 55, 86, 28, 25, 67, 75, 61, 88, 55],
       [55, 55, 26, 22,  1, 22, 22, 46, 81, 23],
       [45, 14, 87, 89,  9, 78, 80, 69,  5, 23],
       [ 7, 83, 42, 63, 96, 40, 11, 55, 99, 96]], dtype=int32)

In [143]:
arr2

array([[70, 81, 99, 81, 53, 18, 39, 35, 11, 21],
       [ 7, 83, 42, 63, 96, 40, 11, 55, 99, 96],
       [74, 33, 90,  8, 81, 33, 36, 94, 53, 76],
       [45, 14, 87, 89,  9, 78, 80, 69,  5, 23],
       [16,  8, 24, 42, 73, 24, 59, 76, 43, 37],
       [55, 55, 26, 22,  1, 22, 22, 46, 81, 23],
       [89, 34, 20, 77,  6, 74, 35, 53, 26, 97],
       [27, 55, 86, 28, 25, 67, 75, 61, 88, 55],
       [80, 27, 74, 86, 93, 34, 70, 54, 93, 87],
       [54, 32, 49, 26, 48, 54, 18, 77, 63,  0]], dtype=int32)

In [144]:
arr2[::-3]

array([[54, 32, 49, 26, 48, 54, 18, 77, 63,  0],
       [89, 34, 20, 77,  6, 74, 35, 53, 26, 97],
       [45, 14, 87, 89,  9, 78, 80, 69,  5, 23],
       [70, 81, 99, 81, 53, 18, 39, 35, 11, 21]], dtype=int32)

In [145]:
arr2

array([[70, 81, 99, 81, 53, 18, 39, 35, 11, 21],
       [ 7, 83, 42, 63, 96, 40, 11, 55, 99, 96],
       [74, 33, 90,  8, 81, 33, 36, 94, 53, 76],
       [45, 14, 87, 89,  9, 78, 80, 69,  5, 23],
       [16,  8, 24, 42, 73, 24, 59, 76, 43, 37],
       [55, 55, 26, 22,  1, 22, 22, 46, 81, 23],
       [89, 34, 20, 77,  6, 74, 35, 53, 26, 97],
       [27, 55, 86, 28, 25, 67, 75, 61, 88, 55],
       [80, 27, 74, 86, 93, 34, 70, 54, 93, 87],
       [54, 32, 49, 26, 48, 54, 18, 77, 63,  0]], dtype=int32)

In [146]:
arr2[:-3]

array([[70, 81, 99, 81, 53, 18, 39, 35, 11, 21],
       [ 7, 83, 42, 63, 96, 40, 11, 55, 99, 96],
       [74, 33, 90,  8, 81, 33, 36, 94, 53, 76],
       [45, 14, 87, 89,  9, 78, 80, 69,  5, 23],
       [16,  8, 24, 42, 73, 24, 59, 76, 43, 37],
       [55, 55, 26, 22,  1, 22, 22, 46, 81, 23],
       [89, 34, 20, 77,  6, 74, 35, 53, 26, 97]], dtype=int32)

## max , min , mean  ,median 

In [160]:
a=np.array([1,2,3,4,5,4,3,2,5,1,2,3,4,2,2,3,3,4])
arr

(1, 2, 3, 4, 5, 4, 3, 2, 5, 1, 2, 3, 4, 2, 2, 3, 3, 4)

In [162]:
print(a.min())

1


In [163]:
print(a.max())

5


In [164]:
a

array([1, 2, 3, 4, 5, 4, 3, 2, 5, 1, 2, 3, 4, 2, 2, 3, 3, 4])

In [165]:
print(a.mean())

2.9444444444444446


In [166]:
print(a.median())

AttributeError: 'numpy.ndarray' object has no attribute 'median'

In [172]:
from numpy import*
a=array([1,2,3,4,5,6])
print(median(a))

3.5


## without working on import* is possible to find the value of mean and median

In [181]:
arr1=np.array([0,1,2,3,4,5])
arr1

array([0, 1, 2, 3, 4, 5])

In [182]:
arr1.reshape(1,6)

array([[0, 1, 2, 3, 4, 5]])

In [183]:
arr1.reshape(6,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [184]:
arr1.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [185]:
arr1.reshape(2,3,order='C')

array([[0, 1, 2],
       [3, 4, 5]])

In [187]:
arr1.reshape(2,3,order='F')

array([[0, 2, 4],
       [1, 3, 5]])

In [188]:
arr1.reshape(2,3,order='A')

array([[0, 1, 2],
       [3, 4, 5]])

## Indexing

In [190]:
mat=np.arange(0,100).reshape(10,10)

In [191]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [192]:
row=4
col=5

In [193]:
row

4

In [194]:
col

5

In [195]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [196]:
mat[row,col]

np.int64(45)

In [197]:
mat[4,5]

np.int64(45)

In [198]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [199]:
mat[:]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [200]:
col=6

In [201]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [202]:
mat[6]

array([60, 61, 62, 63, 64, 65, 66, 67, 68, 69])

In [203]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [204]:
mat[:,col]

array([ 6, 16, 26, 36, 46, 56, 66, 76, 86, 96])

In [205]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [206]:
mat[row,:]

array([40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [207]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [209]:
mat[:,8]

array([ 8, 18, 28, 38, 48, 58, 68, 78, 88, 98])

In [210]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [211]:
mat[:col]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [212]:
mat[:6]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [213]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [218]:
mat[row:]

array([[40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [217]:
mat[:row]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [225]:
mat[:]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [219]:
mat[:8]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79]])

In [222]:
mat[8:]

array([[80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [223]:
mat[-1:]

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [224]:
mat[:-1]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89]])

In [226]:
mat[::-3]

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9]])

In [227]:
mat[2:6,2:4]      # indicates row and column part

array([[22, 23],
       [32, 33],
       [42, 43],
       [52, 53]])

## MASKING

In [228]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [229]:
id(mat)

1811473932112

In [230]:
mat[mat<=50]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [231]:
mat[mat>=50]

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66,
       67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83,
       84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [232]:
mat[mat>50]

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [233]:
mat[mat<50]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [234]:
mat[mat==50]

array([50])

In [235]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [236]:
a1=mat[mat==50]
a2=mat[mat>50]
a3=mat[mat<50]
a4=mat[mat>=50]
a5=mat[mat<=50]

In [237]:
print(a1)      #using print function 
print(a2)
print(a3)
print(a4)
print(a5)

[50]
[51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74
 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98
 99]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49]
[50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73
 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97
 98 99]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50]
